#!/bin/bash
####################################################################
#
#
#
####################################################################

BLFSBOOK_XML=$(pwd)/xml/blfs-xml

[ -d $BLFSBOOK_XML ] && rm -rf $BLFSBOOK_XML

git clone https://git.linuxfromscratch.org/blfs $BLFSBOOK_XML
