#!/bin/bash
####################################################################
# 
# common-defs
#
####################################################################

# dirs
SCRIPTS_DIR=scripts
BUILD_DIR=build
BUILD_CONFIG=$BUILD_DIR/config
BUILD_XML=$BUILD_DIR/xml
XSL_DIR=xsl
BUILDSCRIPTS_DIR=$BUILD_DIR/build-scripts
BLFS_BOOK=$BUILD_XML/blfs-xml
DEPTREE_DIR=$BUILD_DIR/deptree
DEPS_DIR=$DEPTREE_DIR/deps
TREE_DIR=$DEPTREE_DIR/trees
WORK_DIR=$BUILD_DIR/work

# files
INIT_IN=$BUILD_CONFIG/init.in
INIT_OUT=$BUILD_CONFIG/init.out
ROOT_DEPS=$DEPTREE_DIR/root.deps
ROOT_TREE=$DEPTREE_DIR/root.tree
SYSTEMDFULL_XML=$BUILD_XML/blfs-systemd-full.xml
BLFSFULL_XML=$BUILD_XML/blfs-full.xml
SELECT_IN=$BUILD_CONFIG/select.in
SELECT_OUT=$BUILD_CONFIG/select.out
SELECTIN_TMP=$BUILD_CONFIG/select.in.tmp
PROCD_FILE=$DEPTREE_DIR/processed.tmp
VALID_FILE=$BUILD_DIR/validated

# xsl
GENDEPS_XSL=$XSL_DIR/dependencies.xsl
BUILDSCRIPTS_XSL=$XSL_DIR/build-scripts.xsl
SELECTIN_XSL=$XSL_DIR/select-menu.xsl

# scripts
MENU_CONFIG=kconfiglib/menuconfig.py
GENDEPS_SCRIPT=$SCRIPTS_DIR/build-tree.sh



