#!/bin/bash
####################################################################
# 
# common-defs
#
####################################################################

# dirs
SCRIPTS_DIR=$TOPDIR/scripts
BUILD_DIR=$TOPDIR/build
XSL_DIR=$TOPDIR/xsl
BUILD_CONFIG=$BUILD_DIR/config
BUILD_XML=$BUILD_DIR/xml
BUILDSCRIPTS_DIR=$BUILD_DIR/scripts
BLFS_BOOK=$BUILD_XML/blfs-xml
DEPTREE_DIR=$BUILD_DIR/deptree
DEPS_DIR=$DEPTREE_DIR/deps
TREE_DIR=$DEPTREE_DIR/trees
WORK_DIR=$BUILD_DIR/work

# files
INIT_IN=$BUILD_CONFIG/init.in
INIT_OUT=$BUILD_CONFIG/init.out
ROOT_DEPS=$DEPTREE_DIR/root.deps
ROOT_TREE=$DEPTREE_DIR/root.tree
PKG_DEPS=$DEPTREE_DIR/pkg.deps
PKG_TREE=$DEPTREE_DIR/pkg.tree
SYSTEMDFULL_XML=$BUILD_XML/blfs-systemd-full.xml
BLFSFULL_XML=$BUILD_XML/blfs-full.xml
SELECT_IN=$BUILD_CONFIG/select.in
SELECT_OUT=$BUILD_CONFIG/select.out
SELECTIN_TMP=$BUILD_CONFIG/select.in.tmp
PROCD_FILE=$DEPTREE_DIR/processed.tmp
VALID_FILE=$BUILD_DIR/validated
PKGLIST_XSL=$XSL_DIR/pkg-list.xsl
PKGLIST_XML=$BUILD_XML/pkg-list.xml
BUILDSCRIPTS_XSL=$XSL_DIR/build-scripts.xsl
SCRIPTHEADER_XSL=$XSL_DIR/script-header.xsl
SCRIPTDOWNLOADS_XSL=$XSL_DIR/script-downloads.xsl
SCRIPTCOMMANDS_XSL=$XSL_DIR/script-commands.xsl
INSTPKG_XML=/var/lib/jhalfs/BLFS/instpkg.xml
VERSINSTPKG_XSL=$XSL_DIR/vers-instpkg.xsl
ADDINSTALLED_XSL=xsl/add-installed.xsl
BUILD_SCRIPTS=$BUILD_DIR/build.scripts

# xsl
DEPENDENCIES_XSL=$XSL_DIR/dependencies.xsl
BUILDSCRIPTS_XSL=$XSL_DIR/build-scripts.xsl
SELECTIN_XSL=$XSL_DIR/select-menu.xsl

# scripts
MENU_CONFIG=$TOPDIR/kconfiglib/menuconfig.py
GENDEPS_SCRIPT=$SCRIPTS_DIR/build-tree.sh



