#!/bin/bash
####################################################################
#
#
#
####################################################################

KCONFIG_SETUP=$(pwd)/scripts/kconfiglib/Config.setup

cat >  $KCONFIG_SETUP << EOF


menu "TEST SETUP"

endmenu


EOF










